# Generated by Django 3.0.4 on 2020-03-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Balance',
            field=models.DecimalField(decimal_places=5, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Root',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Sold',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Total_Balance',
            field=models.DecimalField(decimal_places=5, max_digits=19, null=True),
        ),
    ]
