# Generated by Django 3.0.4 on 2020-04-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_show'),
    ]

    operations = [
        migrations.DeleteModel(
            name='show',
        ),
    ]
