# Generated by Django 3.0.4 on 2020-04-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_delete_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Root', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Root',
        ),
    ]
