# Generated by Django 3.0.4 on 2020-04-02 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_auto_20200402_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
